# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if (Test-Path -Path %cd%\requirements.txt) {
          pip install -r requirements.txt
        }

    - name: Install dependencies (Mac/Linux)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest (Windows)
      if: runner.os == 'Windows'
      run: |
        set PYTHONPATH=%PYTHONPATH%;cd
        cd test
        bash run-tests.sh

    - name: Test with pytest (Mac/Linux)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        export PYTHONPATH=$PYTHONPATH:`pwd`
        cd test
        ./run-tests.sh
